[project]
name = "backend-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django==5.2.11",
    "django-cors-headers==4.6.0",
    "django-environ==0.11.2",
    "django-ninja==1.5.3",
    "django-ninja-extra==0.31.0",
    "django-ninja-jwt>=5.4",
    "django-q2==1.9.0",
    "django-simple-history==3.8.0",
    "httpx==0.28.1",
    "ninja-schema>=0.14.3",
    "pillow==11.1.0",
    "psycopg2-binary==2.9.10",
    "requests==2.32.3",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "black==24.10.0",
    "django-debug-toolbar==4.4.6",
    "factory-boy>=3.3.3",
    "ipython==8.31.0",
    "pyre-check>=0.9.25",
    "pytest==8.3.4",
    "pytest-cov==6.0.0",
    "pytest-django==4.9.0",
    "ruff==0.8.0",
]
